### ISSUE TITLE
Help Running

### ISSUE THREAD

**Issue by wreck10walls** [youyanggu/groupme_stats#9] opened 2015-12-14 15:04 UTC
Hello, I am extremely new to python, and I would greatly appreciate it if someone could walk me through what to do, step-by-step to get this code to run.

**Comment by youyanggu** [comment] 2015-12-15 01:45
Follow the instructions on the README. For step 2, try running this:

*python retrieve_msgs.py [YOUR TOKEN] -a -c output.csv*

This will output all of your messages into a csv file called output.csv.
Let me know if you have any issues.

**Comment by Osaleh1** [comment] 2015-12-26 19:47
Can't get it to work, and it says that the "retrieve_msgs.py" is a syntax error. Does this mean i need to show the absolute path to the downloaded .py file? And should i be writing this in the Python shell or Terminal on Mac?

**Comment by youyanggu** [comment] 2015-12-26 19:50
This is probably your issue:
http://stackoverflow.com/questions/13961140/syntax-error-when-using-command-line-in-python
.

Run it on the Terminal on Mac.

**Comment by hasselhof** [comment] 2016-02-09 00:08
I am also brand new to python (literally just installed it and added python to the PATH environmental variable). This is my command input & return. Can you please tell me what the issue is? I am also not sure how to handle the Access token bit once I get there...


C:\Users\sheppard>python.exe "c:\Users\sheppard\Documents\retrieve_msgs.py"
  File "c:\Users\sheppard\Documents\retrieve_msgs.py", line 124
    print "Counting messages for", getGroupName(group_id), "( out of", totalCoun
t, ")"
                                ^
SyntaxError: invalid syntax

**Comment by hasselhof** [comment] 2016-02-09 02:11
Solved. Syntax error related to python versions (print command needs parentheses). Seems to be working, though you may want to note this in your readme, as well as the ultimate write location of the csv ouput. Thanks!

**Comment by youyanggu** [comment] 2016-02-12 05:26
Fixed in Issue #10

**Closed by youyanggu** 2016-02-12 05:26 UTC
